Adding sampler write and read functions to sampler.py #1738
m-labs/artiq pull request #1742
Opened 2021-08-06 16:48 UTC by han94ros

# ARTIQ Pull Request

## Description of Changes
Adds sampler_mu_write and sampler_mu_read functions to the sampler core device driver. The purpose is to allow for control of the buffering of samples e.g sampling on a timestamp and then recovering the results at a later time. 

### Related Issue

## Type of Changes

|   | Type |
| ------------- | ------------- |

| ✓  | :sparkles: New feature |

## Steps (Choose relevant, delete irrelevant before submitting)

### All Pull Requests

- [x] Use correct spelling and grammar.
- [ ] Update [RELEASE_NOTES.rst](../RELEASE_NOTES.rst) if there are noteworthy changes, especially if there are changes to existing APIs.
- [ ] Close/update issues.
- [ ] Check the copyright situation of your changes and sign off your patches (`git commit --signoff`, see [copyright](../CONTRIBUTING.rst#copyright-and-sign-off)).

### Code Changes

- [ ] Run `flake8` to check code style (follow PEP-8 style). `flake8` has issues with parsing Migen/gateware code, ignore as necessary.
- [ ] Test your changes or have someone test them. Mention what was tested and how.
- [ ] Add and check docstrings and comments
- [ ] Check, test, and update the [unittests in /artiq/test/](../artiq/test/) or [gateware simulations in /artiq/gateware/test](../artiq/gateware/test)

### Documentation Changes

- [ ] Check, test, and update the documentation in [doc/](../doc/). Build documentation (`cd doc/manual/; make html`) to ensure no errors.

### Git Logistics

- [ ] Split your contribution into logically separate changes (`git rebase --interactive`). Merge/squash/fixup commits that just fix or amend previous commits. Remove unintended changes & cleanup. See [tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase).
- [ ] Write short & meaningful commit messages. Review each commit for messages (`git show`). Format:
  ```
  topic: description. < 50 characters total.
  
  Longer description. < 70 characters per line
  ```

### Licensing

See [copyright & licensing for more info](https://github.com/m-labs/artiq/blob/master/CONTRIBUTING.rst#copyright-and-sign-off).
ARTIQ files that do not contain a license header are copyrighted by M-Labs Limited and are licensed under LGPLv3+.

2021-08-16 09:51 UTC, jordens requested changes
This approach is OK. Just need to meet the minimum requirements.
And please show that you have tested this code.

2021-08-16 09:51 UTC, jordens commented on artiq/coredevice/sampler.py
> +
There are a bunch of checkboxes that you haven't completed yet. One of them is style. Please make some effort to propose quality code that matches the prevalent style and orthography.

2021-08-16 09:51 UTC, jordens commented on artiq/coredevice/sampler.py
> +    def sample_mu_write(self, data):
Then only pass a numer, not a list.

2021-08-16 09:51 UTC, jordens commented on artiq/coredevice/sampler.py
> +    def sample_mu_write(self, data):
This method should then be used in `sample_mu()`.

2021-08-16 09:51 UTC, jordens commented on artiq/coredevice/sampler.py
> +        """prepare ADC.
Please write accurate and quality comments. They will appear in the documentation. "prepare ADC" isn't what this does at all.

2021-08-16 09:51 UTC, jordens commented on artiq/coredevice/sampler.py
> +        Writing appropriate data to shift register and start transfer
Please write entire sentences.

2021-08-16 09:51 UTC, jordens commented on artiq/coredevice/sampler.py
> +    def sample_mu_read(self, data):
This method should then also be used in `sample_mu()`.

2021-08-16 09:51 UTC, jordens commented on artiq/coredevice/sampler.py
> +        """read in the values submitted to the SPI core.
Please write proper docstrings with proper sentences.

2021-12-06 04:53 UTC, closed without merging

2022-09-26 14:26 UTC, han94ros commented
Can you please reopen this PR so that I can finish the tasks.